Feature/capstone 20 edit the student's profile infos page
Capstone-project-team-group-4/language-center-system pull request #23
Opened 2021-04-01 14:31 UTC by DoNgocSonSE04735

Pull request

2021-04-05 17:47 UTC, Phan-Lam-SE03555 requested changes
@DoNgocSonSE04735 Tưởng ông thay đổi tận 39 files là làm được nhiều lắm hóa ra toàn lỗi linh tinh. Sửa hết hộ tôi cái nhé....

2021-04-05 17:47 UTC, Phan-Lam-SE03555 commented on back-end/src/main/java/com/PhanLam/backend/service/LessonService.java
> +    private CourseRepository courseRepository;
@DoNgocSonSE04735 Có dùng course repository không mà bỏ vào đây, không dùng thì xóa đi.

2021-04-05 17:47 UTC, Phan-Lam-SE03555 commented on front-end/.eslintcache
> +[{"C:\\Users\\roboc\\OneDrive\\Desktop\\Capstone\\Project\\language-center-system\\front-end\\src\\index.tsx":"1","C:\\Users\\roboc\\OneDrive\\Desktop\\Capstone\\Project\\language-center-system\\fron
@DoNgocSonSE04735 Khi nào sửa đến file này thì call cho tôi, để tôi xử lý.

2021-04-05 17:47 UTC, Phan-Lam-SE03555 commented on front-end/package.json
> +    "@material-ui/core": "^4.9.14",
@DoNgocSonSE04735 Ông có dùng material-ui không đấy. Có thì giữ dòng này, không thì bỏ đi.

2021-04-05 17:47 UTC, Phan-Lam-SE03555 commented on front-end/package.json
> +    "react": "^16.8.0",
@DoNgocSonSE04735 Sao đang dùng bản 17.0.1 lại chuyển thành 16.8.0 ? Cả team thống nhất dùng 17.0.1 rồi. Ông làm thế này toang hết, upgrade hoặc cài lại đê. Trong doc ghi là dùng 17.0.1 đấy.

2021-04-05 17:47 UTC, Phan-Lam-SE03555 commented on front-end/package.json
> +    "react-dom": "^16.8.0",
@DoNgocSonSE04735 Như trên.

2021-04-05 17:47 UTC, Phan-Lam-SE03555 commented on front-end/src/common/component/PageHeader.tsx
> +                        </Button> */}
@DoNgocSonSE04735 Bỏ comment cho button này nhé.

2021-04-05 17:47 UTC, Phan-Lam-SE03555 commented on front-end/src/model/User.tsx
> +	public firstName: string;
@DoNgocSonSE04735 Sao firstName đang ở trên middleName tự nhiên xóa đi rồi bỏ xuống dưới là như thế nào ?

2021-04-05 17:47 UTC, Phan-Lam-SE03555 commented on front-end/src/page/admin/AdminConsolePage.tsx
> +                                            </Button>
@DoNgocSonSE04735 Bỏ cái button này đi nhé, cái button này phải liên hệ với ông @BuiXuanNhanTriSE05211 để bỏ vào trang của ông ấy.

2021-04-05 17:47 UTC, Phan-Lam-SE03555 commented on front-end/tsconfig.json
> +    ]
@DoNgocSonSE04735 Ô sửa cái này ông có biết là đang làm cái gì không ? Sửa linh tinh lỗi hết cả project đấy, thay đổi lại như cũ hộ cái nhé.

2021-04-05 18:46 UTC, DoNgocSonSE04735 commented on back-end/src/main/java/com/PhanLam/backend/model/Address.java
> +    @NamedQuery(name = "Address.findByCountry", query = "SELECT a FROM Address a WHERE a.country = :country")})
cái này nó tự gen đấy

2021-04-05 18:47 UTC, DoNgocSonSE04735 commented on back-end/src/main/java/com/PhanLam/backend/model/Course.java
> +    public List<Examination> getExaminationList() {
file này t ko đụng đến chắc là format r

2021-04-05 18:48 UTC, DoNgocSonSE04735 commented on back-end/src/main/java/com/PhanLam/backend/dal/repository_interface/CourseRepository.java
> +    public List<Course> findAll();
ok nhé

2021-04-05 18:48 UTC, DoNgocSonSE04735 commented on back-end/src/main/java/com/PhanLam/backend/dal/repository_interface/CourseRepository.java
> +    public Course findCourseById(Integer courseID);
ok

2021-04-05 18:49 UTC, DoNgocSonSE04735 commented on front-end/src/common/component/PageHeader.tsx
> +                        </Button> */}
thế t tạo thêm PageHeader riêng cho Student nhé

2021-04-05 18:49 UTC, DoNgocSonSE04735 commented on front-end/src/common/component/PageHeader.tsx
> +                        </Button> */}
vì Student vào thì làm gì có quyền switch role

2021-04-05 18:50 UTC, DoNgocSonSE04735 commented on front-end/src/model/User.tsx
> +	public firstName: string;
cái này t ko nhớ sao lại vậy

2021-04-05 18:50 UTC, DoNgocSonSE04735 commented on front-end/src/page/admin/AdminConsolePage.tsx
> +                                            </Button>
ok

2021-04-05 18:52 UTC, DoNgocSonSE04735 commented on front-end/tsconfig.json
> +    ]
t chưa hề động đến file này nhé

2021-04-05 18:52 UTC, DoNgocSonSE04735 commented on front-end/tsconfig.json
> +    ]
còn nếu vì sao nó bị thay đổi thì t chịu

2021-04-10 19:36 UTC, Phan-Lam-SE03555 commented on front-end/src/common/component/PageHeader.tsx
> +                        </Button> */}
@DoNgocSonSE04735 Switch role thoải mái nhé nếu như tài khoản đó được cấp nhiều hơn 1 role.

2021-04-10 21:43 UTC, Phan-Lam-SE03555 requested changes
@DoNgocSonSE04735 Sửa hết những cái chưa resolved ở bên trên và những cái mới bên dưới nhé.

2021-04-10 21:43 UTC, Phan-Lam-SE03555 commented on front-end/src/common/component/student_sidebar/StudentSidebar.tsx
> +export function StudentSidebar(): ReactElement {
@DoNgocSonSE04735 Nhắm chiến được phần này không không thì để tôi xử lý. Như lần trước tôi bảo là không hardcoded nhé.

2021-04-10 21:43 UTC, Phan-Lam-SE03555 commented on front-end/src/page/student/StudentDashboardPage.tsx
> +    let a: number[] = [17, 16, 22]
@DoNgocSonSE04735 Không hardcoded nữa nhé.

2021-04-10 21:43 UTC, Phan-Lam-SE03555 commented on front-end/src/page/student/StudentDashboardPage.tsx
> +        courseAPI.getOneCourse(17).then(
@DoNgocSonSE04735 Đây cũng là hardcoded nhé.

2021-04-11 08:06 UTC, DoNgocSonSE04735 commented on back-end/src/main/java/com/PhanLam/backend/configuration/SecurityConfiguration.java
> +                        .hasRole ("ADMIN")
ừ trong student dashboard. Lúc đầu t để role admin bây h t để role Student r

2021-04-11 08:08 UTC, DoNgocSonSE04735 commented on front-end/src/page/student/StudentDashboardPage.tsx
> +    let a: number[] = [17, 16, 22]
ok. cái này t bỏ r

2021-04-11 08:26 UTC, DoNgocSonSE04735 commented on back-end/src/main/java/com/PhanLam/backend/model/User.java
> +import java.util.ArrayList;
t thấy cái multipleChoiceQuestionList dùng arraylist

2021-04-11 08:26 UTC, DoNgocSonSE04735 commented on front-end/.eslintcache
> +[{"C:\\Users\\roboc\\OneDrive\\Desktop\\Capstone\\Project\\language-center-system\\front-end\\src\\index.tsx":"1","C:\\Users\\roboc\\OneDrive\\Desktop\\Capstone\\Project\\language-center-system\\fron
t ko sửa file này

2021-04-11 08:28 UTC, DoNgocSonSE04735 commented on back-end/src/main/java/com/PhanLam/backend/service/LessonService.java
> +    private CourseRepository courseRepository;
ok

2021-04-11 14:08 UTC, DoNgocSonSE04735 commented on front-end/src/common/component/student_sidebar/StudentSidebar.tsx
> +export function StudentSidebar(): ReactElement {
t làm xong phần này r

2021-04-15 07:52 UTC, Phan-Lam-SE03555 requested changes
@DoNgocSonSE04735 Ông sửa nốt 2 cái này là của ông xong nhé.

2021-04-15 09:50 UTC, Phan-Lam-SE03555 approved these changes
@DoNgocSonSE04735 Ok ông merge được rồi đó.

2021-04-15 20:52 UTC, Phan-Lam-SE03555 approved these changes

2021-04-15 20:53 UTC, merged